# This workflow will build a package using Maven and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#apache-maven-with-a-settings-path

name: Java CI to run mvn package

#on:
#  release:
#    types: [created]
on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    # runs-on: windows-latest
    # runs-on: macos-latest

    permissions:
      contents: read
      packages: write

    steps:
    # The checkout step downloads a copy of your repository on the runner
    - uses: actions/checkout@v3
    # The setup-java step configures the Java 11 JDK by Adoptium
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        #distribution: 'adopt'
        architecture: x64
        server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
        settings-path: ${{ github.workspace }} # location for the settings.xml file

    # "Build with Maven" step runs the Maven package target in non-interactive mode
    - name: Build with Maven
      run: mvn --batch-mode --update-snapshots package

    - run: mkdir staging && cp target/*.jar staging
    - uses: actions/upload-artifact@v3
      with:
        name: Package
        path: staging

    #- name: Publish to GitHub Packages Apache Maven
    #  run: mvn deploy -s $GITHUB_WORKSPACE/settings.xml
    #  env:
    #    GITHUB_TOKEN: ${{ github.token }}
